version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: stashhog-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - APP_NAME=StashHog
      - DEBUG=True
      - DATABASE_URL=sqlite:///./stashhog.db
      - STASH_URL=http://host.docker.internal:9999
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: stashhog-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_APP_NAME=StashHog
    command: npm run dev -- --host