version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: stashhog-postgres
    environment:
      - POSTGRES_USER=stashhog
      - POSTGRES_PASSWORD=stashhog-password
      - POSTGRES_DB=stashhog
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stashhog"]
      interval: 10s
      timeout: 5s
      retries: 5

  stashhog:
    image: docker.io/sjafferali/stashhog:latest
    container_name: stashhog
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=StashHog
      - DATABASE_URL=postgresql://stashhog:stashhog-password@postgres:5432/stashhog
      - STASH_URL=http://your-stash-instance:9999
      - STASH_API_KEY=your-stash-api-key
      - OPENAI_API_KEY=your-openai-api-key
      - OPENAI_MODEL=gpt-4-vision-preview
      - SECRET_KEY=change-this-to-a-random-secret-key
      - APP_ENVIRONMENT=production
    restart: unless-stopped

volumes:
  postgres-data: