global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'stashhog-monitor'

scrape_configs:
  - job_name: 'stashhog'
    static_configs:
      - targets: ['stashhog:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'nginx'
    static_configs:
      - targets: ['stashhog:80']
    metrics_path: '/nginx-status'
    scrape_interval: 30s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - 'alerts.yml'